### ISSUE TITLE
是否可以更新一下 openai的接口？

### ISSUE THREAD

**Issue by linkboy2007** [zhuSilence/zsxq-openai#1]
现在支持 turbo3.5了。可以更新一下。。

**Comment by zhuSilence** [comment]
感谢关注，已提供新的脚本。
脚本的修改主要有下面几点
1. 请求地址不一样
2. 请求参数发生变化，多了一个 messages 数组参数；
3. 响应结果有变化，通过 body.choices[0].message.content 字段获取响应；

PS：目前国内好像已经不能访问官网的 API 了，需要梯子~~
